In [1]:
import re
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
df = pd.read_csv('movies.csv')
df.describe()

movieId
count   27278.000000
mean    59855.480570
std     44429.314697
min         1.000000
25%      6931.250000
50%     68068.000000
75%    100293.250000
max    131262.000000

In [3]:
df['title'] = [title.lower()for title in df['title']]
df['title'] = [re.sub('\([0-9]{4}\)', '',  title) for title in df['title']]
df.head()

movieId                         title  \
0        1                    toy story    
1        2                      jumanji    
2        3             grumpier old men    
3        4            waiting to exhale    
4        5  father of the bride part ii    

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [4]:
def getDtm(textList):
    vect = CountVectorizer(ngram_range=(1,1))
    vect.fit(textList)
    return vect.transform(textList)

In [5]:
def getM(textList, query):
    vect = CountVectorizer(ngram_range=(1,1))
    vect.fit(textList)
    return vect.transform(query)

In [6]:
def getQ(textList, m, query, c=2):
    sumM = getSumM(textList, query)
    
    alpha = c*m
    alphaL = alpha + sumM
    beta = c*(1-m)
    betaL = beta + len(textList) - sumM
    
    a = np.log(alphaL)
    a2 = np.log(alpha)
    b = np.log(betaL)
    b2 = np.log(beta)
    
    return a-a2-b+b2

In [7]:
query = ['toy sotry', 'old men']
dtm = getDtm(df['title'])
dtm.shape

(27278, 21887)

In [8]:
x = getM(df['title'], query)
x.todense()
x.shape

(2, 21887)

In [9]:
alpha = 2*np.mean(dtm, axis=0)
beta = 2*(1-np.mean(dtm, axis=0))
beta.shape

(1, 21887)

In [10]:
alphaL = alpha + x.sum(axis=0)
betaL = beta + len(query) - x.sum(axis=0)
betaL.shape

(1, 21887)

In [11]:
q = np.log(alphaL) - np.log(alpha) - np.log(betaL) + np.log(beta)
q.shape

(1, 21887)

In [12]:
nc = np.log(alpha + beta) - np.log(alpha + beta + len(query)) + np.log(betaL) - np.log(beta)
nc
nc.sum(axis=0)


matrix([[3.30099583e-04, 1.83302936e-05, 1.83302936e-05, ...,
         1.83302936e-05, 1.83302936e-05, 1.83302936e-05]])

In [13]:
nc

matrix([[3.30099583e-04, 1.83302936e-05, 1.83302936e-05, ...,
         1.83302936e-05, 1.83302936e-05, 1.83302936e-05]])

In [14]:
dtm.shape

(27278, 21887)

In [16]:
escore = dtm*q.transpose()
escore

matrix([[ 5.77931536],
        [-0.69316551],
        [ 8.74296626],
        ...,
        [-1.62229935],
        [-1.38633102],
        [-0.69338555]])

In [29]:
df['score'] = escore
df.sort_values(by=['score'], ascending=False)

movieId                                              title  \
2            3                                  grumpier old men    
3361      3450                                    grumpy old men    
12216    55820                            no country for old men    
19186    95446                                           tin toy    
5744      5843                                      toy soldiers    
3027      3114                                       toy story 2    
15401    78499                                       toy story 3    
0            1                                         toy story    
4833      4929                                          toy, the    
21772   105271     gathering of old men, a (murder on the bayou)    
11245    47601               7 men from now (seven men from now)    
15773    80141                                christmas toy, the    
9298     27357      old men in new cars (gamle mænd i nye biler)    
993       1012                                        old yeller    
7383      7582                                  old acquaintance    
4536      4631                                        old gringo    
11555    50259                                           old joy    
14523    72696                                          old dogs    
6089      6188                                        old school    
9476     27773                                           old boy    
21981   106022                               toy story of terror    
3702      3793                                             x-men    
11231    47484                                             g men    
1131      1154                                             t-men    
16216    81981                               toy, the (le jouet)    
8358     25760                                 old san francisco    
14588    72960                                  nasty old people    
1426      1463                                  that old feeling    
24097   114250                                       my old lady    
17443    87954                                    in old arizona    
...        ...                                                ...   
19304    95963  dragon ball z: wrath of the dragon (doragon bô...   
19316    96004  dragon ball z: the history of trunks (doragon ...   
5445      5542  nightmare city (a.k.a. city of the walking dea...   
22333   107306  gurren lagann: the lights in the sky are stars...   
23299   110873  centenarian who climbed out the window and van...   
20571   100721  black magic rites & the secret orgies of the 1...   
8464     25901  henry v (chronicle history of king henry the f...   
4960      5056  enigma of kaspar hauser, the (a.k.a. mystery o...   
23559   112179  sudden wealth of the poor people of kombach, t...   
14847    74327  first day of the rest of your life, the (le pr...   
6159      6258  dames du bois de boulogne, les (ladies of the ...   
9198     27103  strange behaviour of sexually mature city slic...   
2605      2691  legend of 1900, the (a.k.a. the legend of the ...   
23319   111031  manufacturing reality: slavoj zizek and the re...   
20052    98829  evil cult, the (lord of the wu tang) (yi tian ...   
14863    74438  legend of the red dragon (a.k.a. new legend of...   
7309      7422  love and anarchy (film d'amore e d'anarchia, o...   
14375    72001  extraordinary adventures of mr. west in the la...   
22173   106702  strange case of dr. jekyll and miss osbourne, ...   
15495    78965  puppetry of the penis: live at the forum (pupp...   
24273   115042  more about the children of noisy village (a.k....   
7706      8224  dexter the dragon & bumble the bear (a.k.a. dr...   
20950   102284  henry iv, part i (first part of king henry the...   
6127      6226  lost honor of katharina blum, the (verlorene e...   
19305    95965  dragon ball z: bardock - the father of goku (d...   
9271     27307  night of the day of the dawn of the son of the...   
14135

In [27]:
pd.DataFrame.sort_values?